import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SideMenuList from '../components/aside-menulist'
import logo from '../assets/yt-logo.jpg'
import {BrandingHeader} from '../components/header/branding'
import LeftAside from '../components/layouts/left-side'
import Main from "../components/layouts/main-content";
import RightAside from "../components/layouts/right-side";
import { GetStaticProps } from "next";
import React, { useState } from 'react';



// ---------------------------------------------------
import fs from "fs";
import path from "path";
import matter from "gray-matter";
import { MDXProvider } from "@mdx-js/react";
import MDX from "@mdx-js/runtime";


const components = {
  h1: (props : any) => (
    <h1 className="fffffffffffffffff" style={{ color: "red" }}>
      {props.children}
    </h1>
  ),
  p: (props : any) => <p style={{ color: "green" }}>{props.children}</p>,
}; 

// -------------------------------------------------------------------------------

export const course_a = [
  {
    id: 3,
    href: "string",
    title: "string",
    extraContent: [{ id: 4, href: "aaaExtrastring", title: "aaaExtraTitle" }],
  },
  { id: 5, href: "5string", title: "5tttttstring" },
  { id: 5, href: "5string", title: "5tttttstring" },
  {
    id: 5,
    href: "5string",
    title: "5tttttstring",
    extraContent: [
      { id: 4, href: "article_1", title: "article_1" },
      { id: 4, href: "aaaExtrastring", title: "Working with Mobile Devices" },
      { id: 4, href: "aaaExtrastring", title: "aaaExtraTitle" },
      {
        id: 4,
        href: "aaaExtrastring",
        title: "Objects, properties and constructor arguments",
      },
    ],
  },
  { id: 5, href: "5string", title: "5tttttstring" },
];

export const leftAsideItems = [
  {
    id: 3,
    href: "string",
    title: "Right Menu iteme1"
  },
  { id: 5, href: "5string", title: "5tttttstring" },
  { id: 5, href: "5string", title: "Item 2" },
  {
    id: 5,
    href: "5string",
    title: "5tttttstring",
  },
  { id: 5, href: "5string", title: "Item 3" },
];

const Home: NextPage = (props : any) => {
  const [slidein, setSlidein] = useState(false);
  return (
    <div className={slidein? `${styles.layout} ${styles.slide}`: styles.layout} >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LeftAside list={course_a} heading={"React Three Fiber"} onSlidein={()=>setSlidein(true)} onSlideout={()=>setSlidein(false)}/>
      <Main>
        <MDXProvider components={components}>
          <MDX components={components}>{props.mdx}</MDX>
        </MDXProvider>
      </Main>
      <RightAside>
        <SideMenuList list={leftAsideItems} />
      </RightAside>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const folderPath = path.join(process.cwd(), "content");
  const filePath = path.join(folderPath, `${'article_1'}.mdx`);
  const rawFileSource = fs.readFileSync(filePath);
  const { content, data } = matter(rawFileSource);
  return {
    props: {
      mdx: content,
      metaInformation: data,
    },
  };
};


export default Home
